# Site settings
title: Jekyll shop powered by Snipcart
email: geeks@snipcart.com
description: Here's a quick demo showing the integration between Snipcart and Jekyll. We hope you like it!
baseurl: "/snipcart-jekyll-integration" # the subpath of your site, e.g. /blog/
url: "http://psychologist-harry-47434.netlify.com" # the base hostname & protocol for your site
twitter_username: Snipcart
github_username:  Snipcart
api_key: ZGFjMjg2MDYtZmZhOC00ODBjLTliYjEtZWZiZTk2NjczOTU2NjM2NDM0Mzk5MTQ2NTk1ODM0

# Build settings
markdown: kramdown
collections:
  products:
    output: true
